### ISSUE TITLE
Square wave quality differences

### ISSUE THREAD

**Issue by alake3777** [howardcc-edu-enes-222/oscilliscopefft-oscope#11]
square waves generated by computers in class are not good
Timmy's laptop was better
Wave generator is even better

**Comment by alake3777** [comment]
A document illustrating the difference between square waves from a signal generator, Timmy's laptop, and the Dell AIOs has been created in the square_wave branch.

**Comment by Leopardopt** [comment]
Yes I agree and that is most likely because of the amount of background process that is going on in HCC computers that causes a lag in waves making them more curvy than what they need to be.
